export type Shift = {
  id: string;
  /** 0 = Mon ... 6 = Sun */
  day: number;
  /** minutes from 00:00 */
  start: number;
  /** minutes from 00:00; may be > start when overnight (we wrap) */
  end: number;
};

export const DAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

const KEY = "shiftrest.shifts.v1";

export function loadShifts(): Shift[] {
  if (typeof window === "undefined") return [];
  try {
    return JSON.parse(localStorage.getItem(KEY) || "[]");
  } catch {
    return [];
  }
}

export function saveShifts(shifts: Shift[]) {
  if (typeof window === "undefined") return;
  localStorage.setItem(KEY, JSON.stringify(shifts));
}

export function fmt(min: number) {
  const m = ((min % 1440) + 1440) % 1440;
  const h = Math.floor(m / 60);
  const mm = m % 60;
  const period = h >= 12 ? "PM" : "AM";
  const h12 = ((h + 11) % 12) + 1;
  return `${h12}:${mm.toString().padStart(2, "0")} ${period}`;
}

export function parseTime(value: string): number {
  // "HH:MM"
  const [h, m] = value.split(":").map(Number);
  return h * 60 + m;
}

export function toTimeInput(min: number): string {
  const m = ((min % 1440) + 1440) % 1440;
  const h = Math.floor(m / 60);
  const mm = m % 60;
  return `${h.toString().padStart(2, "0")}:${mm.toString().padStart(2, "0")}`;
}

/** Returns shift end as absolute minutes (may exceed 1440 if overnight). */
export function endAbsolute(shift: Shift): number {
  return shift.end <= shift.start ? shift.end + 1440 : shift.end;
}

export const DISCLAIMER =
  "Disclaimer: ShiftRest AI and its operators do not provide medical advice. The shift schedules, winding-down windows, and sleep recommendations generated by this application are for educational and optimization purposes only. Always consult a healthcare professional before making major changes to your sleep patterns or health routines.";
