import { createFileRoute, Link } from "@tanstack/react-router";
import { LegalLayout } from "@/components/legal/LegalLayout";
import { findLegalDoc } from "@/lib/legal/meta";

const DOC = findLegalDoc("privacy")!;

export const Route = createFileRoute("/legal/privacy")({
  head: () => ({
    meta: [
      { title: `${DOC.title} — RestPilot AI` },
      { name: "description", content: DOC.summary },
      { property: "og:title", content: `${DOC.title} — RestPilot AI` },
      { property: "og:description", content: DOC.summary },
      { property: "og:url", content: DOC.path },
    ],
    links: [{ rel: "canonical", href: DOC.path }],
  }),
  component: () => (
    <LegalLayout doc={DOC}>
      <p>
        This Privacy Policy explains how RestPilot AI ("we," "us," or "our")
        collects, uses, and protects information when you use our website,
        applications, and related services (the "Service"). For an overview of
        the companies we share data with, see{" "}
        <Link to="/legal/third-parties">Subprocessors &amp; Integrations</Link>.
      </p>

      <h2>1. Information we collect</h2>
      <h3>Information you provide</h3>
      <ul>
        <li>
          <strong>Account:</strong> email address, display name, password hash
          (or OAuth identifier if you sign in with Google).
        </li>
        <li>
          <strong>Profile &amp; preferences:</strong> target sleep hours,
          wind-down preferences, employers, role, notification preferences.
        </li>
        <li>
          <strong>Shifts &amp; planning data:</strong> shifts you log, trips,
          time-zone events, manual feedback you give the AI coach.
        </li>
        <li>
          <strong>Wearable data (optional):</strong> if you connect Fitbit or
          Oura, we receive the sleep, readiness, and activity metrics those
          services share with us.
        </li>
      </ul>

      <h3>Information collected automatically</h3>
      <ul>
        <li>
          <strong>Device &amp; usage:</strong> browser type, operating system,
          coarse approximate timezone, and basic diagnostic info.
        </li>
        <li>
          <strong>Location (only on request):</strong> if you tap "Detect," we
          read approximate latitude/longitude in your browser to compute
          sunrise/sunset for your light plan. We do not continuously track
          location.
        </li>
        <li>
          <strong>Storage on your device:</strong> we use{" "}
          <Link to="/legal/cookies">browser storage</Link> (cookies,
          localStorage, IndexedDB, service-worker cache) to keep you signed in
          and to enable offline mode.
        </li>
      </ul>

      <h3>Information generated by the Service</h3>
      <ul>
        <li>
          <strong>AI memory:</strong> short structured facts the AI extracts
          from your interactions, with your control. See "AI memory" below.
        </li>
        <li>
          <strong>AI logs &amp; recommendations:</strong> records of AI
          decisions and the inputs used to make them.
        </li>
      </ul>

      <h2>2. How we use information</h2>
      <ul>
        <li>To operate, secure, and improve the Service.</li>
        <li>To generate your circadian schedule, alarms, and recovery plan.</li>
        <li>To send notifications you opt into.</li>
        <li>To process payments through our payment processor.</li>
        <li>To comply with law and enforce our agreements.</li>
      </ul>
      <p>
        We do <strong>not</strong> sell your personal information and we do
        not use it for third-party advertising.
      </p>

      <h2>3. Legal bases (EEA/UK users)</h2>
      <p>
        Where the GDPR applies, we process personal data under the following
        bases: performance of a contract (operating the Service), legitimate
        interests (security, product improvement, fraud prevention), consent
        (location, push notifications, wearables, optional AI memory), and
        compliance with legal obligations.
      </p>

      <h2 id="local-storage">4. Local &amp; offline storage</h2>
      <p>
        RestPilot AI is designed to work offline. We cache a copy of your
        current plan and recent recommendations on your device using your
        browser's storage so the app remains useful without a connection. You
        can clear this data at any time by signing out, clearing site data in
        your browser, or uninstalling the installed app.
      </p>

      <h2>5. AI memory</h2>
      <p>
        With your permission, the AI maintains a small set of structured
        memories about you (such as "prefers caffeine cutoff at 14:00") to
        personalize recommendations. You can view, edit, delete, export, and
        disable AI memory entirely from the{" "}
        <Link to="/memory">Memory page</Link>. The AI does not generate
        memories about your health or other sensitive categories.
      </p>

      <h2>6. Retention</h2>
      <table className="w-full text-left text-xs">
        <thead>
          <tr>
            <th className="py-2">Category</th>
            <th className="py-2">Retention</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Account</td>
            <td>Until you delete your account</td>
          </tr>
          <tr>
            <td>Shifts, trips, preferences</td>
            <td>Until you delete them or delete your account</td>
          </tr>
          <tr>
            <td>Wearable readings</td>
            <td>Rolling 365 days; deleted on disconnect</td>
          </tr>
          <tr>
            <td>AI logs</td>
            <td>90 days for diagnostics</td>
          </tr>
          <tr>
            <td>AI recommendations &amp; feedback</td>
            <td>365 days, then aggregated/anonymized</td>
          </tr>
          <tr>
            <td>Billing records</td>
            <td>As required by tax law (typically 7 years)</td>
          </tr>
          <tr>
            <td>Backups</td>
            <td>Rolling 30 days</td>
          </tr>
        </tbody>
      </table>

      <h2>7. Sharing</h2>
      <p>
        We share data with the third-party providers listed in our{" "}
        <Link to="/legal/third-parties">Subprocessors &amp; Integrations</Link>{" "}
        registry only as needed to operate the Service, and with authorities
        when required by law.
      </p>

      <h2>8. International transfers</h2>
      <p>
        Our infrastructure may process data in the United States and the
        European Union. Where required, we rely on Standard Contractual
        Clauses or equivalent safeguards.
      </p>

      <h2>9. Your rights</h2>
      <p>
        Depending on where you live, you may have the right to access,
        correct, port, delete, restrict, or object to processing of your
        personal data, and to withdraw consent at any time. You can exercise
        most of these rights directly from{" "}
        <Link to="/profile">Profile</Link>: download your data, manage AI
        memory, or delete your account. Account deletion is permanent and
        removes associated personal data within 30 days, except where we are
        required to retain it.
      </p>
      <p>
        California residents: under the CCPA/CPRA, you have rights to know,
        delete, correct, and limit use of sensitive personal information. We
        do not "sell" or "share" personal information as defined by the
        CCPA/CPRA.
      </p>

      <h2>10. Security</h2>
      <p>
        Data is transmitted over HTTPS and stored on encrypted servers
        operated by our infrastructure provider. See our{" "}
        <Link to="/legal/security">Security &amp; Responsible Disclosure</Link>
        {" "}page for our security practices and how to report a
        vulnerability.
      </p>

      <h2>11. Children</h2>
      <p>
        The Service is not directed to children under 16, and we do not
        knowingly collect personal information from them. If you believe a
        child has provided us personal information, contact{" "}
        <a href="mailto:support@restpilotai.com">support@restpilotai.com</a>.
      </p>

      <h2>12. Changes</h2>
      <p>
        We will post any changes to this Policy here with an updated
        "Effective" date. Material changes will be highlighted in the app.
      </p>

      <h2>13. Contact</h2>
      <p>
        Email{" "}
        <a href="mailto:support@restpilotai.com">support@restpilotai.com</a> for
        questions or to exercise your rights.
      </p>
    </LegalLayout>
  ),
});
