/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as SmartHomeRouteImport } from './routes/smart-home'
import { Route as SleepRouteImport } from './routes/sleep'
import { Route as ShareRouteImport } from './routes/share'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlaybooksRouteImport } from './routes/playbooks'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PilotRouteImport } from './routes/pilot'
import { Route as PaywallRouteImport } from './routes/paywall'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HealthRouteImport } from './routes/health'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompanionRouteImport } from './routes/companion'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as SettingsSkillsRouteImport } from './routes/settings.skills'
import { Route as SettingsMorningRouteImport } from './routes/settings.morning'
import { Route as SettingsCompanionRouteImport } from './routes/settings.companion'
import { Route as SettingsAvatarRouteImport } from './routes/settings.avatar'
import { Route as QaVoiceRouteImport } from './routes/qa.voice'
import { Route as LegalTrademarkRouteImport } from './routes/legal.trademark'
import { Route as LegalThirdPartiesRouteImport } from './routes/legal.third-parties'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalSubscriptionRouteImport } from './routes/legal.subscription'
import { Route as LegalSecurityRouteImport } from './routes/legal.security'
import { Route as LegalRegionalRouteImport } from './routes/legal.regional'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalOpenSourceRouteImport } from './routes/legal.open-source'
import { Route as LegalLicenseRouteImport } from './routes/legal.license'
import { Route as LegalElectronicConsentRouteImport } from './routes/legal.electronic-consent'
import { Route as LegalDisclaimersRouteImport } from './routes/legal.disclaimers'
import { Route as LegalCopyrightRouteImport } from './routes/legal.copyright'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalAccessibilityRouteImport } from './routes/legal.accessibility'
import { Route as LegalAcceptableUseRouteImport } from './routes/legal.acceptable-use'
import { Route as LabAvatarPocRouteImport } from './routes/lab.avatar-poc'
import { Route as ApiTtsElevenlabsRouteImport } from './routes/api/tts-elevenlabs'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSwapRouteImport } from './routes/api/swap'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as ApiInsightsRouteImport } from './routes/api/insights'
import { Route as ApiCoachRouteImport } from './routes/api/coach'
import { Route as ApiBriefRouteImport } from './routes/api/brief'
import { Route as ApiAiRouteImport } from './routes/api/ai'
import { Route as LabAvatarPocSimliRouteImport } from './routes/lab.avatar-poc.simli'
import { Route as LabAvatarPocDebugRouteImport } from './routes/lab.avatar-poc.debug'
import { Route as ApiPublicWearablesCronRouteImport } from './routes/api/public/wearables/cron'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksNotifyRouteImport } from './routes/api/public/hooks/notify'
import { Route as ApiPublicHooksAiLearnRouteImport } from './routes/api/public/hooks/ai-learn'
import { Route as ApiLabSimliSpeakRouteImport } from './routes/api/lab/simli/speak'
import { Route as ApiLabSimliSessionRouteImport } from './routes/api/lab/simli/session'
import { Route as ApiPublicWearablesOuraCallbackRouteImport } from './routes/api/public/wearables/oura/callback'
import { Route as ApiPublicWearablesFitbitCallbackRouteImport } from './routes/api/public/wearables/fitbit/callback'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartHomeRoute = SmartHomeRouteImport.update({
  id: '/smart-home',
  path: '/smart-home',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepRoute = SleepRouteImport.update({
  id: '/sleep',
  path: '/sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksRoute = PlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotRoute = PilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const PaywallRoute = PaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionRoute = CompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegalRoute,
} as any)
const SettingsSkillsRoute = SettingsSkillsRouteImport.update({
  id: '/settings/skills',
  path: '/settings/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMorningRoute = SettingsMorningRouteImport.update({
  id: '/settings/morning',
  path: '/settings/morning',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCompanionRoute = SettingsCompanionRouteImport.update({
  id: '/settings/companion',
  path: '/settings/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAvatarRoute = SettingsAvatarRouteImport.update({
  id: '/settings/avatar',
  path: '/settings/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const QaVoiceRoute = QaVoiceRouteImport.update({
  id: '/qa/voice',
  path: '/qa/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTrademarkRoute = LegalTrademarkRouteImport.update({
  id: '/trademark',
  path: '/trademark',
  getParentRoute: () => LegalRoute,
} as any)
const LegalThirdPartiesRoute = LegalThirdPartiesRouteImport.update({
  id: '/third-parties',
  path: '/third-parties',
  getParentRoute: () => LegalRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalSubscriptionRoute = LegalSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => LegalRoute,
} as any)
const LegalSecurityRoute = LegalSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => LegalRoute,
} as any)
const LegalRegionalRoute = LegalRegionalRouteImport.update({
  id: '/regional',
  path: '/regional',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalOpenSourceRoute = LegalOpenSourceRouteImport.update({
  id: '/open-source',
  path: '/open-source',
  getParentRoute: () => LegalRoute,
} as any)
const LegalLicenseRoute = LegalLicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => LegalRoute,
} as any)
const LegalElectronicConsentRoute = LegalElectronicConsentRouteImport.update({
  id: '/electronic-consent',
  path: '/electronic-consent',
  getParentRoute: () => LegalRoute,
} as any)
const LegalDisclaimersRoute = LegalDisclaimersRouteImport.update({
  id: '/disclaimers',
  path: '/disclaimers',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCopyrightRoute = LegalCopyrightRouteImport.update({
  id: '/copyright',
  path: '/copyright',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LegalRoute,
} as any)
const LegalAccessibilityRoute = LegalAccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => LegalRoute,
} as any)
const LegalAcceptableUseRoute = LegalAcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => LegalRoute,
} as any)
const LabAvatarPocRoute = LabAvatarPocRouteImport.update({
  id: '/lab/avatar-poc',
  path: '/lab/avatar-poc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsElevenlabsRoute = ApiTtsElevenlabsRouteImport.update({
  id: '/api/tts-elevenlabs',
  path: '/api/tts-elevenlabs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwapRoute = ApiSwapRouteImport.update({
  id: '/api/swap',
  path: '/api/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInsightsRoute = ApiInsightsRouteImport.update({
  id: '/api/insights',
  path: '/api/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachRoute = ApiCoachRouteImport.update({
  id: '/api/coach',
  path: '/api/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBriefRoute = ApiBriefRouteImport.update({
  id: '/api/brief',
  path: '/api/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const LabAvatarPocSimliRoute = LabAvatarPocSimliRouteImport.update({
  id: '/simli',
  path: '/simli',
  getParentRoute: () => LabAvatarPocRoute,
} as any)
const LabAvatarPocDebugRoute = LabAvatarPocDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => LabAvatarPocRoute,
} as any)
const ApiPublicWearablesCronRoute = ApiPublicWearablesCronRouteImport.update({
  id: '/api/public/wearables/cron',
  path: '/api/public/wearables/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNotifyRoute = ApiPublicHooksNotifyRouteImport.update({
  id: '/api/public/hooks/notify',
  path: '/api/public/hooks/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAiLearnRoute = ApiPublicHooksAiLearnRouteImport.update({
  id: '/api/public/hooks/ai-learn',
  path: '/api/public/hooks/ai-learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLabSimliSpeakRoute = ApiLabSimliSpeakRouteImport.update({
  id: '/api/lab/simli/speak',
  path: '/api/lab/simli/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLabSimliSessionRoute = ApiLabSimliSessionRouteImport.update({
  id: '/api/lab/simli/session',
  path: '/api/lab/simli/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWearablesOuraCallbackRoute =
  ApiPublicWearablesOuraCallbackRouteImport.update({
    id: '/api/public/wearables/oura/callback',
    path: '/api/public/wearables/oura/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWearablesFitbitCallbackRoute =
  ApiPublicWearablesFitbitCallbackRouteImport.update({
    id: '/api/public/wearables/fitbit/callback',
    path: '/api/public/wearables/fitbit/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automations': typeof AutomationsRoute
  '/coach': typeof CoachRoute
  '/companion': typeof CompanionRoute
  '/dashboard': typeof DashboardRoute
  '/decisions': typeof DecisionsRoute
  '/events': typeof EventsRoute
  '/features': typeof FeaturesRoute
  '/health': typeof HealthRoute
  '/inbox': typeof InboxRoute
  '/legal': typeof LegalRouteWithChildren
  '/memory': typeof MemoryRoute
  '/paywall': typeof PaywallRoute
  '/pilot': typeof PilotRoute
  '/plan': typeof PlanRoute
  '/playbooks': typeof PlaybooksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/share': typeof ShareRoute
  '/sleep': typeof SleepRoute
  '/smart-home': typeof SmartHomeRoute
  '/swap': typeof SwapRoute
  '/terms': typeof TermsRoute
  '/api/ai': typeof ApiAiRoute
  '/api/brief': typeof ApiBriefRoute
  '/api/coach': typeof ApiCoachRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/stt': typeof ApiSttRoute
  '/api/swap': typeof ApiSwapRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/tts-elevenlabs': typeof ApiTtsElevenlabsRoute
  '/lab/avatar-poc': typeof LabAvatarPocRouteWithChildren
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/copyright': typeof LegalCopyrightRoute
  '/legal/disclaimers': typeof LegalDisclaimersRoute
  '/legal/electronic-consent': typeof LegalElectronicConsentRoute
  '/legal/license': typeof LegalLicenseRoute
  '/legal/open-source': typeof LegalOpenSourceRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/regional': typeof LegalRegionalRoute
  '/legal/security': typeof LegalSecurityRoute
  '/legal/subscription': typeof LegalSubscriptionRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/third-parties': typeof LegalThirdPartiesRoute
  '/legal/trademark': typeof LegalTrademarkRoute
  '/qa/voice': typeof QaVoiceRoute
  '/settings/avatar': typeof SettingsAvatarRoute
  '/settings/companion': typeof SettingsCompanionRoute
  '/settings/morning': typeof SettingsMorningRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/legal/': typeof LegalIndexRoute
  '/lab/avatar-poc/debug': typeof LabAvatarPocDebugRoute
  '/lab/avatar-poc/simli': typeof LabAvatarPocSimliRoute
  '/api/lab/simli/session': typeof ApiLabSimliSessionRoute
  '/api/lab/simli/speak': typeof ApiLabSimliSpeakRoute
  '/api/public/hooks/ai-learn': typeof ApiPublicHooksAiLearnRoute
  '/api/public/hooks/notify': typeof ApiPublicHooksNotifyRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/wearables/cron': typeof ApiPublicWearablesCronRoute
  '/api/public/wearables/fitbit/callback': typeof ApiPublicWearablesFitbitCallbackRoute
  '/api/public/wearables/oura/callback': typeof ApiPublicWearablesOuraCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automations': typeof AutomationsRoute
  '/coach': typeof CoachRoute
  '/companion': typeof CompanionRoute
  '/dashboard': typeof DashboardRoute
  '/decisions': typeof DecisionsRoute
  '/events': typeof EventsRoute
  '/features': typeof FeaturesRoute
  '/health': typeof HealthRoute
  '/inbox': typeof InboxRoute
  '/memory': typeof MemoryRoute
  '/paywall': typeof PaywallRoute
  '/pilot': typeof PilotRoute
  '/plan': typeof PlanRoute
  '/playbooks': typeof PlaybooksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/share': typeof ShareRoute
  '/sleep': typeof SleepRoute
  '/smart-home': typeof SmartHomeRoute
  '/swap': typeof SwapRoute
  '/terms': typeof TermsRoute
  '/api/ai': typeof ApiAiRoute
  '/api/brief': typeof ApiBriefRoute
  '/api/coach': typeof ApiCoachRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/stt': typeof ApiSttRoute
  '/api/swap': typeof ApiSwapRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/tts-elevenlabs': typeof ApiTtsElevenlabsRoute
  '/lab/avatar-poc': typeof LabAvatarPocRouteWithChildren
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/copyright': typeof LegalCopyrightRoute
  '/legal/disclaimers': typeof LegalDisclaimersRoute
  '/legal/electronic-consent': typeof LegalElectronicConsentRoute
  '/legal/license': typeof LegalLicenseRoute
  '/legal/open-source': typeof LegalOpenSourceRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/regional': typeof LegalRegionalRoute
  '/legal/security': typeof LegalSecurityRoute
  '/legal/subscription': typeof LegalSubscriptionRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/third-parties': typeof LegalThirdPartiesRoute
  '/legal/trademark': typeof LegalTrademarkRoute
  '/qa/voice': typeof QaVoiceRoute
  '/settings/avatar': typeof SettingsAvatarRoute
  '/settings/companion': typeof SettingsCompanionRoute
  '/settings/morning': typeof SettingsMorningRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/legal': typeof LegalIndexRoute
  '/lab/avatar-poc/debug': typeof LabAvatarPocDebugRoute
  '/lab/avatar-poc/simli': typeof LabAvatarPocSimliRoute
  '/api/lab/simli/session': typeof ApiLabSimliSessionRoute
  '/api/lab/simli/speak': typeof ApiLabSimliSpeakRoute
  '/api/public/hooks/ai-learn': typeof ApiPublicHooksAiLearnRoute
  '/api/public/hooks/notify': typeof ApiPublicHooksNotifyRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/wearables/cron': typeof ApiPublicWearablesCronRoute
  '/api/public/wearables/fitbit/callback': typeof ApiPublicWearablesFitbitCallbackRoute
  '/api/public/wearables/oura/callback': typeof ApiPublicWearablesOuraCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automations': typeof AutomationsRoute
  '/coach': typeof CoachRoute
  '/companion': typeof CompanionRoute
  '/dashboard': typeof DashboardRoute
  '/decisions': typeof DecisionsRoute
  '/events': typeof EventsRoute
  '/features': typeof FeaturesRoute
  '/health': typeof HealthRoute
  '/inbox': typeof InboxRoute
  '/legal': typeof LegalRouteWithChildren
  '/memory': typeof MemoryRoute
  '/paywall': typeof PaywallRoute
  '/pilot': typeof PilotRoute
  '/plan': typeof PlanRoute
  '/playbooks': typeof PlaybooksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/share': typeof ShareRoute
  '/sleep': typeof SleepRoute
  '/smart-home': typeof SmartHomeRoute
  '/swap': typeof SwapRoute
  '/terms': typeof TermsRoute
  '/api/ai': typeof ApiAiRoute
  '/api/brief': typeof ApiBriefRoute
  '/api/coach': typeof ApiCoachRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/stt': typeof ApiSttRoute
  '/api/swap': typeof ApiSwapRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/tts-elevenlabs': typeof ApiTtsElevenlabsRoute
  '/lab/avatar-poc': typeof LabAvatarPocRouteWithChildren
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/copyright': typeof LegalCopyrightRoute
  '/legal/disclaimers': typeof LegalDisclaimersRoute
  '/legal/electronic-consent': typeof LegalElectronicConsentRoute
  '/legal/license': typeof LegalLicenseRoute
  '/legal/open-source': typeof LegalOpenSourceRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/regional': typeof LegalRegionalRoute
  '/legal/security': typeof LegalSecurityRoute
  '/legal/subscription': typeof LegalSubscriptionRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/third-parties': typeof LegalThirdPartiesRoute
  '/legal/trademark': typeof LegalTrademarkRoute
  '/qa/voice': typeof QaVoiceRoute
  '/settings/avatar': typeof SettingsAvatarRoute
  '/settings/companion': typeof SettingsCompanionRoute
  '/settings/morning': typeof SettingsMorningRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/legal/': typeof LegalIndexRoute
  '/lab/avatar-poc/debug': typeof LabAvatarPocDebugRoute
  '/lab/avatar-poc/simli': typeof LabAvatarPocSimliRoute
  '/api/lab/simli/session': typeof ApiLabSimliSessionRoute
  '/api/lab/simli/speak': typeof ApiLabSimliSpeakRoute
  '/api/public/hooks/ai-learn': typeof ApiPublicHooksAiLearnRoute
  '/api/public/hooks/notify': typeof ApiPublicHooksNotifyRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/wearables/cron': typeof ApiPublicWearablesCronRoute
  '/api/public/wearables/fitbit/callback': typeof ApiPublicWearablesFitbitCallbackRoute
  '/api/public/wearables/oura/callback': typeof ApiPublicWearablesOuraCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/automations'
    | '/coach'
    | '/companion'
    | '/dashboard'
    | '/decisions'
    | '/events'
    | '/features'
    | '/health'
    | '/inbox'
    | '/legal'
    | '/memory'
    | '/paywall'
    | '/pilot'
    | '/plan'
    | '/playbooks'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/safety'
    | '/share'
    | '/sleep'
    | '/smart-home'
    | '/swap'
    | '/terms'
    | '/api/ai'
    | '/api/brief'
    | '/api/coach'
    | '/api/insights'
    | '/api/stt'
    | '/api/swap'
    | '/api/tts'
    | '/api/tts-elevenlabs'
    | '/lab/avatar-poc'
    | '/legal/acceptable-use'
    | '/legal/accessibility'
    | '/legal/cookies'
    | '/legal/copyright'
    | '/legal/disclaimers'
    | '/legal/electronic-consent'
    | '/legal/license'
    | '/legal/open-source'
    | '/legal/privacy'
    | '/legal/regional'
    | '/legal/security'
    | '/legal/subscription'
    | '/legal/terms'
    | '/legal/third-parties'
    | '/legal/trademark'
    | '/qa/voice'
    | '/settings/avatar'
    | '/settings/companion'
    | '/settings/morning'
    | '/settings/skills'
    | '/legal/'
    | '/lab/avatar-poc/debug'
    | '/lab/avatar-poc/simli'
    | '/api/lab/simli/session'
    | '/api/lab/simli/speak'
    | '/api/public/hooks/ai-learn'
    | '/api/public/hooks/notify'
    | '/api/public/payments/webhook'
    | '/api/public/wearables/cron'
    | '/api/public/wearables/fitbit/callback'
    | '/api/public/wearables/oura/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/automations'
    | '/coach'
    | '/companion'
    | '/dashboard'
    | '/decisions'
    | '/events'
    | '/features'
    | '/health'
    | '/inbox'
    | '/memory'
    | '/paywall'
    | '/pilot'
    | '/plan'
    | '/playbooks'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/safety'
    | '/share'
    | '/sleep'
    | '/smart-home'
    | '/swap'
    | '/terms'
    | '/api/ai'
    | '/api/brief'
    | '/api/coach'
    | '/api/insights'
    | '/api/stt'
    | '/api/swap'
    | '/api/tts'
    | '/api/tts-elevenlabs'
    | '/lab/avatar-poc'
    | '/legal/acceptable-use'
    | '/legal/accessibility'
    | '/legal/cookies'
    | '/legal/copyright'
    | '/legal/disclaimers'
    | '/legal/electronic-consent'
    | '/legal/license'
    | '/legal/open-source'
    | '/legal/privacy'
    | '/legal/regional'
    | '/legal/security'
    | '/legal/subscription'
    | '/legal/terms'
    | '/legal/third-parties'
    | '/legal/trademark'
    | '/qa/voice'
    | '/settings/avatar'
    | '/settings/companion'
    | '/settings/morning'
    | '/settings/skills'
    | '/legal'
    | '/lab/avatar-poc/debug'
    | '/lab/avatar-poc/simli'
    | '/api/lab/simli/session'
    | '/api/lab/simli/speak'
    | '/api/public/hooks/ai-learn'
    | '/api/public/hooks/notify'
    | '/api/public/payments/webhook'
    | '/api/public/wearables/cron'
    | '/api/public/wearables/fitbit/callback'
    | '/api/public/wearables/oura/callback'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/automations'
    | '/coach'
    | '/companion'
    | '/dashboard'
    | '/decisions'
    | '/events'
    | '/features'
    | '/health'
    | '/inbox'
    | '/legal'
    | '/memory'
    | '/paywall'
    | '/pilot'
    | '/plan'
    | '/playbooks'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/safety'
    | '/share'
    | '/sleep'
    | '/smart-home'
    | '/swap'
    | '/terms'
    | '/api/ai'
    | '/api/brief'
    | '/api/coach'
    | '/api/insights'
    | '/api/stt'
    | '/api/swap'
    | '/api/tts'
    | '/api/tts-elevenlabs'
    | '/lab/avatar-poc'
    | '/legal/acceptable-use'
    | '/legal/accessibility'
    | '/legal/cookies'
    | '/legal/copyright'
    | '/legal/disclaimers'
    | '/legal/electronic-consent'
    | '/legal/license'
    | '/legal/open-source'
    | '/legal/privacy'
    | '/legal/regional'
    | '/legal/security'
    | '/legal/subscription'
    | '/legal/terms'
    | '/legal/third-parties'
    | '/legal/trademark'
    | '/qa/voice'
    | '/settings/avatar'
    | '/settings/companion'
    | '/settings/morning'
    | '/settings/skills'
    | '/legal/'
    | '/lab/avatar-poc/debug'
    | '/lab/avatar-poc/simli'
    | '/api/lab/simli/session'
    | '/api/lab/simli/speak'
    | '/api/public/hooks/ai-learn'
    | '/api/public/hooks/notify'
    | '/api/public/payments/webhook'
    | '/api/public/wearables/cron'
    | '/api/public/wearables/fitbit/callback'
    | '/api/public/wearables/oura/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AutomationsRoute: typeof AutomationsRoute
  CoachRoute: typeof CoachRoute
  CompanionRoute: typeof CompanionRoute
  DashboardRoute: typeof DashboardRoute
  DecisionsRoute: typeof DecisionsRoute
  EventsRoute: typeof EventsRoute
  FeaturesRoute: typeof FeaturesRoute
  HealthRoute: typeof HealthRoute
  InboxRoute: typeof InboxRoute
  LegalRoute: typeof LegalRouteWithChildren
  MemoryRoute: typeof MemoryRoute
  PaywallRoute: typeof PaywallRoute
  PilotRoute: typeof PilotRoute
  PlanRoute: typeof PlanRoute
  PlaybooksRoute: typeof PlaybooksRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SafetyRoute: typeof SafetyRoute
  ShareRoute: typeof ShareRoute
  SleepRoute: typeof SleepRoute
  SmartHomeRoute: typeof SmartHomeRoute
  SwapRoute: typeof SwapRoute
  TermsRoute: typeof TermsRoute
  ApiAiRoute: typeof ApiAiRoute
  ApiBriefRoute: typeof ApiBriefRoute
  ApiCoachRoute: typeof ApiCoachRoute
  ApiInsightsRoute: typeof ApiInsightsRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiSwapRoute: typeof ApiSwapRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiTtsElevenlabsRoute: typeof ApiTtsElevenlabsRoute
  LabAvatarPocRoute: typeof LabAvatarPocRouteWithChildren
  QaVoiceRoute: typeof QaVoiceRoute
  SettingsAvatarRoute: typeof SettingsAvatarRoute
  SettingsCompanionRoute: typeof SettingsCompanionRoute
  SettingsMorningRoute: typeof SettingsMorningRoute
  SettingsSkillsRoute: typeof SettingsSkillsRoute
  ApiLabSimliSessionRoute: typeof ApiLabSimliSessionRoute
  ApiLabSimliSpeakRoute: typeof ApiLabSimliSpeakRoute
  ApiPublicHooksAiLearnRoute: typeof ApiPublicHooksAiLearnRoute
  ApiPublicHooksNotifyRoute: typeof ApiPublicHooksNotifyRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicWearablesCronRoute: typeof ApiPublicWearablesCronRoute
  ApiPublicWearablesFitbitCallbackRoute: typeof ApiPublicWearablesFitbitCallbackRoute
  ApiPublicWearablesOuraCallbackRoute: typeof ApiPublicWearablesOuraCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-home': {
      id: '/smart-home'
      path: '/smart-home'
      fullPath: '/smart-home'
      preLoaderRoute: typeof SmartHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep': {
      id: '/sleep'
      path: '/sleep'
      fullPath: '/sleep'
      preLoaderRoute: typeof SleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks': {
      id: '/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof PlaybooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot': {
      id: '/pilot'
      path: '/pilot'
      fullPath: '/pilot'
      preLoaderRoute: typeof PilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paywall': {
      id: '/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof PaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion': {
      id: '/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof CompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof LegalRoute
    }
    '/settings/skills': {
      id: '/settings/skills'
      path: '/settings/skills'
      fullPath: '/settings/skills'
      preLoaderRoute: typeof SettingsSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/morning': {
      id: '/settings/morning'
      path: '/settings/morning'
      fullPath: '/settings/morning'
      preLoaderRoute: typeof SettingsMorningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/companion': {
      id: '/settings/companion'
      path: '/settings/companion'
      fullPath: '/settings/companion'
      preLoaderRoute: typeof SettingsCompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/avatar': {
      id: '/settings/avatar'
      path: '/settings/avatar'
      fullPath: '/settings/avatar'
      preLoaderRoute: typeof SettingsAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/voice': {
      id: '/qa/voice'
      path: '/qa/voice'
      fullPath: '/qa/voice'
      preLoaderRoute: typeof QaVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/trademark': {
      id: '/legal/trademark'
      path: '/trademark'
      fullPath: '/legal/trademark'
      preLoaderRoute: typeof LegalTrademarkRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/third-parties': {
      id: '/legal/third-parties'
      path: '/third-parties'
      fullPath: '/legal/third-parties'
      preLoaderRoute: typeof LegalThirdPartiesRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/subscription': {
      id: '/legal/subscription'
      path: '/subscription'
      fullPath: '/legal/subscription'
      preLoaderRoute: typeof LegalSubscriptionRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/security': {
      id: '/legal/security'
      path: '/security'
      fullPath: '/legal/security'
      preLoaderRoute: typeof LegalSecurityRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/regional': {
      id: '/legal/regional'
      path: '/regional'
      fullPath: '/legal/regional'
      preLoaderRoute: typeof LegalRegionalRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/open-source': {
      id: '/legal/open-source'
      path: '/open-source'
      fullPath: '/legal/open-source'
      preLoaderRoute: typeof LegalOpenSourceRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/license': {
      id: '/legal/license'
      path: '/license'
      fullPath: '/legal/license'
      preLoaderRoute: typeof LegalLicenseRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/electronic-consent': {
      id: '/legal/electronic-consent'
      path: '/electronic-consent'
      fullPath: '/legal/electronic-consent'
      preLoaderRoute: typeof LegalElectronicConsentRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/disclaimers': {
      id: '/legal/disclaimers'
      path: '/disclaimers'
      fullPath: '/legal/disclaimers'
      preLoaderRoute: typeof LegalDisclaimersRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/copyright': {
      id: '/legal/copyright'
      path: '/copyright'
      fullPath: '/legal/copyright'
      preLoaderRoute: typeof LegalCopyrightRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/accessibility': {
      id: '/legal/accessibility'
      path: '/accessibility'
      fullPath: '/legal/accessibility'
      preLoaderRoute: typeof LegalAccessibilityRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/acceptable-use': {
      id: '/legal/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/legal/acceptable-use'
      preLoaderRoute: typeof LegalAcceptableUseRouteImport
      parentRoute: typeof LegalRoute
    }
    '/lab/avatar-poc': {
      id: '/lab/avatar-poc'
      path: '/lab/avatar-poc'
      fullPath: '/lab/avatar-poc'
      preLoaderRoute: typeof LabAvatarPocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts-elevenlabs': {
      id: '/api/tts-elevenlabs'
      path: '/api/tts-elevenlabs'
      fullPath: '/api/tts-elevenlabs'
      preLoaderRoute: typeof ApiTtsElevenlabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swap': {
      id: '/api/swap'
      path: '/api/swap'
      fullPath: '/api/swap'
      preLoaderRoute: typeof ApiSwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/insights': {
      id: '/api/insights'
      path: '/api/insights'
      fullPath: '/api/insights'
      preLoaderRoute: typeof ApiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach': {
      id: '/api/coach'
      path: '/api/coach'
      fullPath: '/api/coach'
      preLoaderRoute: typeof ApiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brief': {
      id: '/api/brief'
      path: '/api/brief'
      fullPath: '/api/brief'
      preLoaderRoute: typeof ApiBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/avatar-poc/simli': {
      id: '/lab/avatar-poc/simli'
      path: '/simli'
      fullPath: '/lab/avatar-poc/simli'
      preLoaderRoute: typeof LabAvatarPocSimliRouteImport
      parentRoute: typeof LabAvatarPocRoute
    }
    '/lab/avatar-poc/debug': {
      id: '/lab/avatar-poc/debug'
      path: '/debug'
      fullPath: '/lab/avatar-poc/debug'
      preLoaderRoute: typeof LabAvatarPocDebugRouteImport
      parentRoute: typeof LabAvatarPocRoute
    }
    '/api/public/wearables/cron': {
      id: '/api/public/wearables/cron'
      path: '/api/public/wearables/cron'
      fullPath: '/api/public/wearables/cron'
      preLoaderRoute: typeof ApiPublicWearablesCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notify': {
      id: '/api/public/hooks/notify'
      path: '/api/public/hooks/notify'
      fullPath: '/api/public/hooks/notify'
      preLoaderRoute: typeof ApiPublicHooksNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ai-learn': {
      id: '/api/public/hooks/ai-learn'
      path: '/api/public/hooks/ai-learn'
      fullPath: '/api/public/hooks/ai-learn'
      preLoaderRoute: typeof ApiPublicHooksAiLearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lab/simli/speak': {
      id: '/api/lab/simli/speak'
      path: '/api/lab/simli/speak'
      fullPath: '/api/lab/simli/speak'
      preLoaderRoute: typeof ApiLabSimliSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lab/simli/session': {
      id: '/api/lab/simli/session'
      path: '/api/lab/simli/session'
      fullPath: '/api/lab/simli/session'
      preLoaderRoute: typeof ApiLabSimliSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wearables/oura/callback': {
      id: '/api/public/wearables/oura/callback'
      path: '/api/public/wearables/oura/callback'
      fullPath: '/api/public/wearables/oura/callback'
      preLoaderRoute: typeof ApiPublicWearablesOuraCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wearables/fitbit/callback': {
      id: '/api/public/wearables/fitbit/callback'
      path: '/api/public/wearables/fitbit/callback'
      fullPath: '/api/public/wearables/fitbit/callback'
      preLoaderRoute: typeof ApiPublicWearablesFitbitCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LegalRouteChildren {
  LegalAcceptableUseRoute: typeof LegalAcceptableUseRoute
  LegalAccessibilityRoute: typeof LegalAccessibilityRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalCopyrightRoute: typeof LegalCopyrightRoute
  LegalDisclaimersRoute: typeof LegalDisclaimersRoute
  LegalElectronicConsentRoute: typeof LegalElectronicConsentRoute
  LegalLicenseRoute: typeof LegalLicenseRoute
  LegalOpenSourceRoute: typeof LegalOpenSourceRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRegionalRoute: typeof LegalRegionalRoute
  LegalSecurityRoute: typeof LegalSecurityRoute
  LegalSubscriptionRoute: typeof LegalSubscriptionRoute
  LegalTermsRoute: typeof LegalTermsRoute
  LegalThirdPartiesRoute: typeof LegalThirdPartiesRoute
  LegalTrademarkRoute: typeof LegalTrademarkRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalAcceptableUseRoute: LegalAcceptableUseRoute,
  LegalAccessibilityRoute: LegalAccessibilityRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalCopyrightRoute: LegalCopyrightRoute,
  LegalDisclaimersRoute: LegalDisclaimersRoute,
  LegalElectronicConsentRoute: LegalElectronicConsentRoute,
  LegalLicenseRoute: LegalLicenseRoute,
  LegalOpenSourceRoute: LegalOpenSourceRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRegionalRoute: LegalRegionalRoute,
  LegalSecurityRoute: LegalSecurityRoute,
  LegalSubscriptionRoute: LegalSubscriptionRoute,
  LegalTermsRoute: LegalTermsRoute,
  LegalThirdPartiesRoute: LegalThirdPartiesRoute,
  LegalTrademarkRoute: LegalTrademarkRoute,
  LegalIndexRoute: LegalIndexRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface LabAvatarPocRouteChildren {
  LabAvatarPocDebugRoute: typeof LabAvatarPocDebugRoute
  LabAvatarPocSimliRoute: typeof LabAvatarPocSimliRoute
}

const LabAvatarPocRouteChildren: LabAvatarPocRouteChildren = {
  LabAvatarPocDebugRoute: LabAvatarPocDebugRoute,
  LabAvatarPocSimliRoute: LabAvatarPocSimliRoute,
}

const LabAvatarPocRouteWithChildren = LabAvatarPocRoute._addFileChildren(
  LabAvatarPocRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AutomationsRoute: AutomationsRoute,
  CoachRoute: CoachRoute,
  CompanionRoute: CompanionRoute,
  DashboardRoute: DashboardRoute,
  DecisionsRoute: DecisionsRoute,
  EventsRoute: EventsRoute,
  FeaturesRoute: FeaturesRoute,
  HealthRoute: HealthRoute,
  InboxRoute: InboxRoute,
  LegalRoute: LegalRouteWithChildren,
  MemoryRoute: MemoryRoute,
  PaywallRoute: PaywallRoute,
  PilotRoute: PilotRoute,
  PlanRoute: PlanRoute,
  PlaybooksRoute: PlaybooksRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SafetyRoute: SafetyRoute,
  ShareRoute: ShareRoute,
  SleepRoute: SleepRoute,
  SmartHomeRoute: SmartHomeRoute,
  SwapRoute: SwapRoute,
  TermsRoute: TermsRoute,
  ApiAiRoute: ApiAiRoute,
  ApiBriefRoute: ApiBriefRoute,
  ApiCoachRoute: ApiCoachRoute,
  ApiInsightsRoute: ApiInsightsRoute,
  ApiSttRoute: ApiSttRoute,
  ApiSwapRoute: ApiSwapRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiTtsElevenlabsRoute: ApiTtsElevenlabsRoute,
  LabAvatarPocRoute: LabAvatarPocRouteWithChildren,
  QaVoiceRoute: QaVoiceRoute,
  SettingsAvatarRoute: SettingsAvatarRoute,
  SettingsCompanionRoute: SettingsCompanionRoute,
  SettingsMorningRoute: SettingsMorningRoute,
  SettingsSkillsRoute: SettingsSkillsRoute,
  ApiLabSimliSessionRoute: ApiLabSimliSessionRoute,
  ApiLabSimliSpeakRoute: ApiLabSimliSpeakRoute,
  ApiPublicHooksAiLearnRoute: ApiPublicHooksAiLearnRoute,
  ApiPublicHooksNotifyRoute: ApiPublicHooksNotifyRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicWearablesCronRoute: ApiPublicWearablesCronRoute,
  ApiPublicWearablesFitbitCallbackRoute: ApiPublicWearablesFitbitCallbackRoute,
  ApiPublicWearablesOuraCallbackRoute: ApiPublicWearablesOuraCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
